### ISSUE TITLE
On 64-bit Windows, 'findExec' thinks it's 32-bit

### ISSUE THREAD

**Issue by lh64** [RuleWorld/bionetgen#140]
The current code in BNGModel::findExec looks at the size of the long integer in determining the bitness of the OS in Windows, i.e., 

my $bitness = $Config{longsize}*8;

However, longs are apparently 4 bits in Windows no matter the bitness, so this fails. We need to find a robust solution before releasing BNG 2.2.6-stable.

**Comment by jjtapia** [comment]
Since we now provide different packages for each OS, this was solved by removing OS labels from the binary file name.
