### ISSUE TITLE
This issue can be closed.

### ISSUE THREAD

**Issue by rhclark** [RuleWorld/bionetgen#147]
I'm seeing the following output from RuleBender, and I think that it might be coming from BioNetGen or the BioNetGen browser.   If so,  could someone switch it off ?   I wouldn't mind doing it myself, but I don't want to mess up what you're working on now.  Here's the output:

INFO: Parsed Expression: INGROUP('compartments')
Aug 11, 2015 6:08:59 PM prefuse.data.expression.parser.ExpressionParser parse
INFO: Parsed Expression: INGROUP('aggregates')
Aug 11, 2015 6:08:59 PM prefuse.data.expression.parser.ExpressionParser parse
INFO: Parsed Expression: INGROUP('aggregates_component')
Aug 11, 2015 6:08:59 PM prefuse.data.expression.parser.ExpressionParser parse
INFO: Parsed Expression: INGROUP('bubbles')
Aug 11, 2015 6:08:59 PM prefuse.data.expression.parser.ExpressionParser parse
INFO: Parsed Expression: INGROUP('selected')

**Comment by jjtapia** [comment]
Ok

**Comment by rhclark** [comment]
It doesn't seem to be coming from Prefuse, even though Prefuse is written all over it.

**Comment by jjtapia** [comment]
I'm positive none of this comes from BioNetGen.

**Comment by rhclark** [comment]
Oh ok.    I'm still looking at the Prefuse code, and I'm still not finding it there.   It's sort of confusing.

**Comment by rhclark** [comment]
I just found some other text (not shown above) in the RuleBender interface to Prefuse.   So this will probably lead me to the source of the output.  It's strange, though, that I'm not able to find the string "INGROUP".  Oh well.   Thanks for the help.  I'll close out this issue.
