### ISSUE TITLE
Parsing errors in comparison operators

### ISSUE THREAD

**Issue by jrfaeder** [RuleWorld/bionetgen#179]
The attached file reveals a parsing error for expressions using comparison operators with the '=' character. The first instance of '==' or '!=' seems to get truncated to '=' in BNG. This causes BNG to throw an error when the correct syntax is used. In the attached example, an extra '=' is added to the test a==b in order to be able to run BNG without an error. The RuleBender parser complains, but the model runs correctly because BNG removes the extra '=' character. 
[model1ss.bngl.txt](https://github.com/RuleWorld/bionetgen/files/498689/model1ss.bngl.txt)

**Comment by lh64** [comment]
This issue was fixed in [this commit](https://github.com/RuleWorld/bionetgen/commit/1e5302013ca2bb071bbe91124efe0c786d3d402d). I verified that the attached model runs in the repository version of the BNG code but not in BNG 2.2.6. It will be part of the BNG 2.3.0 release coming soon.
