### ISSUE TITLE
atomizer and _libsbml

### ISSUE THREAD

**Issue by glucksfall** [RuleWorld/bionetgen#197]
Hello everyone,

I hope you can help me to install atomizer. I found two errors while running `make` from the source dir. I cloned the bionetgen repository and added the submodules atomizer and NFsim.

The first issue is `./build_sbmlTranslator_linux.sh: line 3: virtualenv2: command not found` and after
`20170 INFO: Analyzing hidden import '_libsbml'`
`20171 ERROR: Hidden import '_libsbml' not found`

That is probably an error installing libsbml for python2 using pip.

Thank you,
best regards

**Comment by jczech** [comment]
I'm currently in the process of updating the build system. On some systems, Python 2's virtualenv is called virtualenv2. This is obviously not the case on yours. If you need an immediate solution, you could revert it back to simply virtualenv. Also you'd probably need to change pip2->pip and python2->python. I should have a more robust solution shortly.

**Comment by glucksfall** [comment]
Hi Jacob,
Thanks for the suggestion. Now I'm trying to figure out how to rid off `ERROR: Hidden import '_libsbml' not found`. Best regards

**Comment by lh64** [comment]
Hi Rodrigo. I think you have to install libsbml for Python (http://sbml.org/Software/libSBML/Downloading_libSBML). Have you done that?

**Comment by glucksfall** [comment]
Hi Leonard,
I installed python-libsbml (and python-libsbml-experimental) using pip for python2 and 3. I can import _libsbml with python2 and with python3 using `from libsbml import _libsbml` (I don't know if it's relevant). Moreover, I understand that build_sbmlTranslator_linux.sh use a virtualenv that download python-libsbml and doesn't rely on the system packages. So, I'm out of ideas why its fail to find _libsbml

**Comment by jjtapia** [comment]
Hello Rodrigo,

Atomizer is written for Python 2.7 so it's best that you use that. 

The `_libsbml` dependency on the binary builder is something  I added to address issues on Mac systems sometimes not getting all the dependencies right. I observed that sometimes it throws an error on Linux systems but the binary is correctly generated at the end regardless. Would you mind posting the full error trace? (e.g. is this error the last thing that is printed or is there something afterwards?)

**Comment by jczech** [comment]
Hi Rodrigo,

What OS are you using? If it's linux, what distro and version?

**Comment by glucksfall** [comment]
Hello Jacob and Jose,

The error after running sbmlTranslator is
```
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/opt/git-ruleworld-bionetgen-master/bng2/atomizer/pyinstaller2/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/opt/git-ruleworld-bionetgen-master/bng2/atomizer/build/sbmlTranslator/out00-PYZ.pyz/libsbml2bngl", line 11, in <module>
  File "/opt/git-ruleworld-bionetgen-master/bng2/atomizer/pyinstaller2/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/opt/git-ruleworld-bionetgen-master/bng2/atomizer/build/sbmlTranslator/out00-PYZ.pyz/libsbml", line 22, in <module>
  File "/opt/git-ruleworld-bionetgen-master/bng2/atomizer/build/sbmlTranslator/out00-PYZ.pyz/libsbml", line 21, in swig_import_helper
  File "/opt/git-ruleworld-bionetgen-master/bng2/atomizer/build/sbmlTranslator/out00-PYZ.pyz/importlib", line 37, in import_module
ImportError: No module named _libsbml
```

This happen in Ubuntu 17.10 and also in Ubuntu 16.04.3

**Comment by glucksfall** [comment]
I closed this issue because last night I compiled without any problem BioNetGen following the Github repository instructions.
Best regards to all.
