### ISSUE TITLE
Is there any way of getting more detail on simulation progress?

### ISSUE THREAD

**Issue by iustin94** [RuleWorld/bionetgen#207]
I have some issues with figuring out if my simulations are going to be successful or not. I end up modifying some parameters and the run time jumps up but I have no idea if they will complete or not. The simulation progress bar stays in the middle and the process runs for minutes or hours with no result.

Is there any way to have more feedback on the progress of a simulation? Or at least know if for example a parameter ends up set wrongly at the beginning? For example several times I would define a reaction rate dependent on a compound that was not at all present in the initial phase.

**Comment by wshlavacek** [comment]
The progress bar provides ZERO information about how long a simulation will
take. It just indicates that a simulation is in progress.

**Comment by jrfaeder** [comment]
Good points. It's hard to predict how long a simulation is going to take, especially for ODE simulations. The stiff solver we use by default can have a long startup time. I'm not sure that the solver itself could provide an estimate of the integration time. That said, I can think about pre-checks that we could do to give a user feedback on when something might be wrong. At the moment, we are not able to make new RuleBender distributions, but we should have a handle on that soon and we will get back to this issue.

**Comment by iustin94** [comment]
I think the prechecks would improve the workflow a lot and that is always welcome. As far as simulation time prediction goes, I realize it's a hard task, that's why I was thinking instead of providing feedback related to how many time steps have been written to the file. For example, whenever a simulation stalls for me, I can see in the .cdat and .gdat files a single entry for the time step and it stays at one. An easier alternative to the progress bar could be to include a count for the calculated time steps so far out of the total number provided in the command arguments :)

**Comment by lh64** [comment]
Hi Iustinian. If you pass the ‘verbose=>1’ argument to the ‘simulate’ command BNG will print info about the simulation to the screen as it’s running, like what time point it’s currently on, etc. That will probably help a lot.

Leonard

**Comment by lh64** [comment]
I think this can be closed
