### ISSUE TITLE
Python could be clearer about lack of perl

### ISSUE THREAD

**Issue by luciansmith** [RuleWorld/bionetgen#244]
When you load a file using the python bindings with

```
bionetgen.bngmodel(bngl_filename)
```

If perl is not installed and runnable via the command line, you get the error (on Windows):

```
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

However, the 'file specified' in question is *perl*, not bngl_filename.  This caused me no end of confusion until I stepped through the code to find where the error was actually generated.

**Comment by jonrkarr** [comment]
I think this error may specifically apply to PyBioNetGen. Also reporte as RuleWorld/PyBioNetGen#41

**Comment by jrfaeder** [comment]
Thanks @jonrkarr for raising this as a PyBNG issue. Closing here as it's not within bionetgen codebase.
