### ISSUE TITLE
Use parameters as arguments in actions

### ISSUE THREAD

**Issue by jrfaeder** [RuleWorld/bionetgen#258]
Currently, if you try to pass a parameter value to actions, you will get an error if you refer to the parameter without enclosing it in quotation marks, and it will evaluate to 0 if you do enclose in quotation marks. In the latter case, it gets interpreted as a string, but then evaluates to zero. 
[paramtest.bngl.txt](https://github.com/RuleWorld/bionetgen/files/9102695/paramtest.bngl.txt)

**Comment by ASinanSaglam** [comment]
Duplicate of #146, closing
