### ISSUE TITLE
Add support for use of parameters in simulate settings, such as t_start=>t0, where t0 is defined in the parameters block.

### ISSUE THREAD

**Issue by wshlavacek** [RuleWorld/bionetgen#273]
In some cases, it would be nice to be able to reference parameters in simulate settings.
For example, t_start=>t0, where t0 is a parameter. Currently, t_start can only be assigned a numerical value.
I'm attaching a BNGL file that illustrates a case where it would be helpful to be able to define an initial "time" using a parameter.
[normal.bngl.txt](https://github.com/RuleWorld/bionetgen/files/14604840/normal.bngl.txt)

**Comment by jrfaeder** [comment]
This feature was added in commit https://github.com/RuleWorld/bionetgen/commit/06d5f6f2e612d3e32a644e1744ec24834780ad6b.
A demonstration file was added here: https://github.com/RuleWorld/bionetgen/blob/master/Issues/273/action_parameter.bngl.

**Note 1:**  Any expression can be used to set both `t_start` and `t_end` but it must be quoted, for example:
`simulate({method=>"ssa",t_start=>"t0",t_end=>"t1",n_steps=>200})`. Failure to include the quotation marks will cause the Perl interpreter to generate an error, which, depending on the context in which BNG is run, may fail to generate an informative message. 

**Note 2.** The `setConcentration` function also allows the concentration argument to be an expression. In fact the code used to process the expression string was used in making the current enhancement for the `simulate` command.

I will wait from comment from @wshlavacek before closing the issue.

**Comment by wshlavacek** [comment]
Thanks Jim!
I tested the new feature and it worked. Thanks for the note about setConcentration, which is good to know.
